# -*- coding: utf-8 -*-
"""Test101-ClinicalBERT-application.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgYnz3twddhjWEGnF4jI-5PTR7WLRRUL
"""

!pip install transformers tensorflow streamlit

import streamlit as st
from transformers import TFAutoModelForSequenceClassification, AutoTokenizer
import tensorflow as tf

# Load the ClinicalBERT model and tokenizer
model_name = "emilyalsentzer/Bio_ClinicalBERT"
model = TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Function to predict the symptoms
def predict_symptom(text):
    inputs = tokenizer(text, return_tensors="tf", truncation=True, padding=True, max_length=512)
    outputs = model(inputs)
    logits = outputs.logits
    probabilities = tf.nn.softmax(logits, axis=-1).numpy()

    # For simplicity, assume binary classification; adjust as needed
    labels = ["No issue", "Consult a doctor"]
    predicted_label = labels[tf.argmax(probabilities, axis=-1).numpy()[0]]

    return predicted_label, probabilities

# Streamlit interface
st.title("ClinicalBERT Symptom Analysis")

user_input = st.text_area("Enter your symptoms:")

if st.button("Analyze"):
    if user_input:
        predicted_label, probabilities = predict_symptom(user_input)
        st.write("Prediction:", predicted_label)
        st.write("Probabilities:", probabilities)
    else:
        st.write("Please enter your symptoms.")